Add mailer
VovchikD/post pull request #10
Opened 2023-11-02 16:08 UTC by VovchikD

Create mailer action and view.Send email when receiving a comment.

2023-11-03 07:06 UTC, vanyavasylyshyn commented on app/controllers/comments_controller.rb
> +        CommentMailer.new_comment(author, @comment).deliver_now
deliver_later

2023-11-03 07:08 UTC, vanyavasylyshyn requested changes
Comment + add tests

2023-11-03 07:09 UTC, vanyavasylyshyn commented on Gemfile
> +  gem 'letter_opener'
add version

2023-11-03 20:15 UTC, vanyavasylyshyn commented on spec/controller/comments_controller_spec.rb
> +      expect(ActionMailer::Base.deliveries.size).to be_present
маєш кількість перевіряти а не те, що воно присутнє
0.present? буде true але тест буде проходити хоч то не правильно, бо треба аби було 1

2023-11-03 20:16 UTC, vanyavasylyshyn commented on spec/factories/user.rb
> +  factory :another_user, class: User do
видалити, що за another юзер?
ти завжди можеш передати кастомні параметри у фекторі коли створюєш, наприклад
`let(:user) { create(:user, email: "some@mail.com")` і по аналогії з любими параметрами

2023-11-05 11:20 UTC, vanyavasylyshyn commented on .rubocop.yml
> +  Enabled: false
має бути тру

2023-11-05 11:20 UTC, vanyavasylyshyn commented on .rubocop.yml
>    Enabled: false
тут тоже має бути вклчюене, якщо замало то постав на довжину 10 і на блок тоже 10

2023-11-05 11:21 UTC, vanyavasylyshyn commented on app/controllers/comments_controller.rb
> +      redirect_to post_path(params[:post_id])
чому не post_path(@post)

2023-11-05 11:22 UTC, vanyavasylyshyn commented on app/controllers/posts_controller.rb
> +    @post = Post.new(post_params.merge(user: current_user))
👍🏻

2023-11-05 11:23 UTC, vanyavasylyshyn commented on .rubocop.yml
> +Style/ParenthesesAroundCondition:
має бути включене

2023-11-05 11:23 UTC, vanyavasylyshyn commented on .rubocop.yml
> +Style/IfUnlessModifier:
має бути включене

2023-11-05 17:02 UTC, vanyavasylyshyn commented on .gitignore
> +/.rubocop.yml
забрати

2023-11-07 12:44 UTC, vanyavasylyshyn commented on .rubocop.yml
> +  Enabled: false
зроби виключеним для контролерів

2023-11-07 12:47 UTC, vanyavasylyshyn commented on .rubocop.yml
> +  Include:
чоловічку, це обовязково має бути включене в контрлерах ))

2023-11-07 12:47 UTC, vanyavasylyshyn commented on .rubocop.yml
> +  Include:
Воно показує наскільки складрний твій код

2023-11-07 12:48 UTC, vanyavasylyshyn commented on app/controllers/comments_controller.rb
> +  def author
ти тут маєш лише автора присвоювати бо в тебе метод називається автор, а не надсилання імейлу

метод завжди має виконувати те що закладено в його назві, якщо робиться щось лишнє це уже не добре

2023-11-07 12:50 UTC, vanyavasylyshyn commented on app/views/devise/passwords/edit.html.erb
> +<div class="flex min-h-screen items-center justify-center">
що це за erb файли, звідки вони взялись? чому не слім?

2023-11-07 12:51 UTC, vanyavasylyshyn commented on config/environments/development.rb
> +  # Група налаштувань для розробки
не можна писати коменти укр мовою, принято англійською
 повидаляй взагалі, вони не потрібні, завжди можна знайти для чого конфіги в документації гему

2023-11-09 07:02 UTC, vanyavasylyshyn commented on spec/controller/comments_controller_spec.rb
> +  it 'send an email to the post author' do
ти тут просто тестуэш чи працюэ мейл, але у тебе немаэ тесту де тестується що коли лишаєш комент на пост то надсилається мейл

2023-11-13 07:22 UTC, vanyavasylyshyn commented on config/environments/development.rb
> +def configure_database_and_logging(config)
що це за метод і нащо він тут, звідки він взявся? і де він викликається?

2023-11-13 07:23 UTC, vanyavasylyshyn commented on db/seeds.rb
> +User.create(
не будуть працювати сіди, подумай сам чого

2023-11-13 07:23 UTC, vanyavasylyshyn commented on spec/controller/comments_controller_spec.rb
> +    post :create, params: { comment: { content: 'A comment' }, post_id: first_post.id, user_id: user.id }
для чого тут user_id? у мене учора все без нього працювало

2023-11-13 10:35 UTC, VovchikD commented on config/environments/development.rb
> +def configure_database_and_logging(config)
Та цей метод був у цьому блоці Rails.application.configure  я просто його винис бо рубокоп сварився шо довгий блок виходить.Цей метод для конфігурацій бази даних я думаю що він викликається у database.yml

2023-11-13 10:38 UTC, VovchikD commented on config/environments/development.rb
> +def configure_database_and_logging(config)
> Я виніс у сетод із цього блока Rails.application.configure бо рубокоп сварився шо довгий блок виходить.Цей метод для конфігурацій бази даних я думаю що він викликається у database.yml

2023-11-13 13:02 UTC, vanyavasylyshyn commented on config/environments/development.rb
> +def configure_database_and_logging(config)
верни назад, таке не можна робити в конфігураціях, добав у рубокоп в правило де довжина блоку аби не перевіряло в файлах енвайроменту

2023-11-13 19:10 UTC, vanyavasylyshyn approved these changes

2023-11-14 10:40 UTC, merged